INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

DATASET:
  NAME: "ImageCLEF"
  SOURCE_DOMAINS: ["b", "c", "i"]
  TARGET_DOMAINS: ["p"]
# you can modify the code to explore four domains

MODEL:
  BACKBONE:
    NAME: "RN50"
