INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_flip", "center_crop", "normalize"]

DATASET:
  NAME: "Office31"
  SOURCE_DOMAINS: ["amazon"]
  TARGET_DOMAINS: ["webcam"]

MODEL:
  BACKBONE:
    NAME: "resnet50"
